# Generated by Django 4.2.4 on 2023-09-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование элемента')),
                ('alt', models.CharField(max_length=255, verbose_name='Alt описание картинки')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок элемента')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание элемента')),
                ('image_large', models.ImageField(upload_to='media/gallery/', verbose_name='Картинка в исходном разрешении')),
                ('image_small', models.ImageField(upload_to='media/gallery/', verbose_name='Картинка для превью')),
            ],
            options={
                'verbose_name': 'Элемент галереи',
                'verbose_name_plural': 'Элементы галереи',
            },
        ),
    ]
