# Generated by Django 4.2.4 on 2023-10-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image_large',
            field=models.ImageField(upload_to='gallery/', verbose_name='Картинка в исходном разрешении'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image_small',
            field=models.ImageField(upload_to='gallery/', verbose_name='Картинка для превью'),
        ),
    ]
