# Generated by Django 4.2.4 on 2024-04-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_galleryitem_image_large_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('text', models.CharField(max_length=30, verbose_name='Текст на плашке')),
                ('background', models.CharField(choices=[('bg-primary', 'Синий'), ('bg-secondary', 'Серый'), ('bg-success', 'Зеленый'), ('bg-danger', 'Красный'), ('bg-dark', 'Черный')], default='bg-success', max_length=30, verbose_name='Цвет фона плашки')),
            ],
            options={
                'verbose_name': 'Плашка',
                'verbose_name_plural': 'Плашки',
            },
        ),
    ]
