# Generated by Django 4.2.4 on 2024-04-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='background',
            field=models.CharField(choices=[('bg-primary', 'Синий'), ('bg-secondary', 'Серый'), ('bg-success', 'Зеленый'), ('bg-danger', 'Красный'), ('bg-dark', 'Черный'), ('bg-green', 'Фирменный зеленый'), ('bg-brown', 'Фирменный коричневый')], default='bg-success', max_length=30, verbose_name='Цвет фона плашки'),
        ),
    ]
