# Generated by Django 4.2.4 on 2023-09-04 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('active', models.BooleanField(default=False, help_text='Выберите компанию в качестве основной. Текущая основная компания потеряет этот статус', verbose_name='Активность')),
                ('name', models.CharField(help_text='Укажите наименование компании для отображения в заголовках сайта', max_length=255, verbose_name='Наименование')),
                ('phone', models.CharField(help_text='Основной телефон компании, который отображается в верхнем меню сайта и в подвале сайта', max_length=255, verbose_name='Основной номер телефона')),
                ('address', models.CharField(help_text='Адрес компании, который отображается в подвале сайта', max_length=255, verbose_name='Адрес')),
                ('logo_header', models.ImageField(blank=True, help_text='Файл логотипа компании в шапке в формате png, рекомендованный размер 60x60 px с прозрачным фоном', upload_to='media/img/logo/', verbose_name='Файл логотипа компании в шапке')),
                ('logo_footer', models.ImageField(blank=True, help_text='Файл логотипа компании в подвале в формате png, рекомендованный размер 60x60 px с прозрачным фоном', upload_to='media/img/logo/', verbose_name='Файл логотипа компании в подвале')),
                ('favicon', models.ImageField(blank=True, help_text='Файл favicon в формате ico', upload_to='media/img/favicon/', verbose_name='Файл favicon')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('floor', models.PositiveSmallIntegerField(default=1, verbose_name='Количество этажей')),
                ('restroom', models.PositiveSmallIntegerField(default=1, verbose_name='Количество комнат отдыха')),
                ('max_guests', models.PositiveSmallIntegerField(default=10, verbose_name='Максимальное количество гостей')),
                ('cost_include', models.CharField(blank=True, max_length=128, verbose_name='Стоимость включает')),
                ('cleaning', models.PositiveSmallIntegerField(default=0, help_text='Если 0, то уборка отсутствует', verbose_name='Время на уборку в минутах')),
                ('gallery_items', models.ManyToManyField(related_name='house_gallery_item', to='common.galleryitem', verbose_name='Элементы галереи')),
                ('photo_main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='house_photo_main', to='common.galleryitem', verbose_name='Основное фото')),
            ],
            options={
                'verbose_name': 'Парная',
                'verbose_name_plural': 'Парные',
            },
        ),
    ]
