# Generated by Django 4.2.4 on 2023-09-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
