# Generated by Django 4.2.4 on 2023-10-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reserve_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Файл favicon в формате ico', upload_to='img/favicon/', verbose_name='Файл favicon'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_footer',
            field=models.ImageField(blank=True, help_text='Файл логотипа компании в подвале в формате png, рекомендованный размер 60x60 px с прозрачным фоном', upload_to='img/logo/', verbose_name='Файл логотипа компании в подвале'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_header',
            field=models.ImageField(blank=True, help_text='Файл логотипа компании в шапке в формате png, рекомендованный размер 60x60 px с прозрачным фоном', upload_to='img/logo/', verbose_name='Файл логотипа компании в шапке'),
        ),
    ]
