# Generated by Django 4.2.4 on 2023-10-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_company_favicon_alter_company_logo_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
