# Generated by Django 4.2.4 on 2023-11-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_reserve_unique_together_remove_rate_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='min_time',
            field=models.PositiveSmallIntegerField(default=3, help_text='Минимальное время парения в часах', verbose_name='Минимальное время парения'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cleaning',
            field=models.PositiveSmallIntegerField(default=0, help_text='Если 0, то уборка отсутствует', verbose_name='Время на уборку в часах'),
        ),
    ]
