# Generated by Django 4.2.4 on 2023-11-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_additionalservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='guests_in_price',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Количество гостей, включенных в стоимость'),
        ),
    ]
