# Generated by Django 4.2.4 on 2023-11-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_house_guests_in_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('date', models.DateField(verbose_name='Дата праздника')),
            ],
            options={
                'verbose_name': 'Праздничный день',
                'verbose_name_plural': 'Праздничные дни',
            },
        ),
    ]
