# Generated by Django 4.2.4 on 2023-11-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_weekenddays'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('icon', models.ImageField(upload_to='img/social/', verbose_name='Иконка')),
                ('show_header', models.BooleanField(default=False, verbose_name='Показывать в шапке')),
                ('show_footer', models.BooleanField(default=False, verbose_name='Показывать в подвале')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='social_networks',
            field=models.ManyToManyField(blank=True, related_name='company_social_networks', to='core.socialnetworks', verbose_name='Социальные сети'),
        ),
    ]
