# Generated by Django 4.2.4 on 2023-11-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_socialnetworks_company_social_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworks',
            name='show_block_booking',
            field=models.BooleanField(default=False, verbose_name='Показывать в блоке бронирования'),
        ),
    ]
