# Generated by Django 4.2.4 on 2023-12-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reserveservices_reserve_additional_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserveservices',
            options={'verbose_name': 'Дополнительная услуга для бронирования', 'verbose_name_plural': 'Дополнительные услуги для бронирования'},
        ),
        migrations.AlterField(
            model_name='reserve',
            name='additional_services',
            field=models.ManyToManyField(blank=True, through='core.ReserveServices', to='core.additionalservices', verbose_name='Дополнительные услуги'),
        ),
        migrations.AlterField(
            model_name='reserveservices',
            name='additional_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.additionalservices', verbose_name='Дополнительная услуга'),
        ),
        migrations.AlterField(
            model_name='reserveservices',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='reserveservices',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='reserveservices',
            name='reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reserve', verbose_name='Бронирование'),
        ),
    ]
