# Generated by Django 4.2.4 on 2023-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_reserveservices_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveservices',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Общая стоимость'),
        ),
    ]
