# Generated by Django 4.2.4 on 2023-12-15 06:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_reserveservices_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=2048, verbose_name='Описание')),
                ('include', ckeditor.fields.RichTextField(help_text='Что вас ждет в программе парения', verbose_name='Программа включает')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
                ('measure', models.CharField(choices=[(None, 'Не выбрано'), ('piece', 'шт.'), ('service', 'усл.'), ('hour', 'час'), ('guest', 'гостя')], default='Не выбрано', max_length=20, verbose_name='Стоимость за')),
                ('duration', models.PositiveSmallIntegerField(help_text='Продолжительность программы парения в минутах', verbose_name='Продолжительность, мин.')),
                ('header_image', models.ImageField(blank=True, help_text='Изображение отображается в шапке карточки на странице Спа-программы', upload_to='img/spa/', verbose_name='Файл основного изображения')),
                ('id_catalog_b24', models.PositiveIntegerField(blank=True, help_text='ID товара/услуги в каталоге Битрикс24', null=True, verbose_name='ID товара/услуги')),
            ],
            options={
                'verbose_name': 'Программа парения',
                'verbose_name_plural': 'Программы парения',
            },
        ),
    ]
