# Generated by Django 4.2.4 on 2023-12-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_priceforspaservices_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='id_b24',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ID ресурса бронирования в Битрикс24', null=True, verbose_name='ID ресурса бронирования в Б24'),
        ),
    ]
