# Generated by Django 4.2.4 on 2023-12-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_house_id_b24'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsBitrix24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('webhook', models.URLField(blank=True, help_text='Webhook для интеграции с Битрикс24', null=True, verbose_name='Webhook')),
            ],
            options={
                'verbose_name': 'Настройки для Битрикс24',
                'verbose_name_plural': 'Настройки для Битрикс24',
            },
        ),
    ]
