# Generated by Django 4.2.4 on 2024-01-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_settingsbitrix24'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsbitrix24',
            name='responsible_by_default',
            field=models.PositiveIntegerField(default=1, help_text='ID ответственного, который будет подставляться при создании сущностей CRM', verbose_name='Ответственный по умолчанию'),
        ),
    ]
