# Generated by Django 4.2.4 on 2024-01-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_settingsbitrix24_responsible_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveservices',
            name='id_b24',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ID товарной позиции в Б24'),
        ),
        migrations.AddField(
            model_name='settingsbitrix24',
            name='stage_id_for_deal_adding',
            field=models.PositiveSmallIntegerField(default=6, help_text='ID стадии воронки сделок для создания сделки бронирования с сайта в CRM', verbose_name='ID стадии для создания сделки'),
        ),
    ]
