# Generated by Django 4.2.4 on 2024-01-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_reserveservices_id_b24_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='deal_id_b24',
            field=models.PositiveIntegerField(blank=True, help_text='ID сделки в Битрикс24', null=True, verbose_name='ID сделки в Битрикс24'),
        ),
    ]
