# Generated by Django 4.2.4 on 2024-01-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_reserve_deal_id_b24'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='id_rent_in_catalog_b24',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID товара аренды в каталоге Битрикс24'),
        ),
        migrations.AddField(
            model_name='rate',
            name='id_rent_weekend_in_catalog_b24',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID товара аренды выходного дня в каталоге Битрикс24'),
        ),
    ]
