# Generated by Django 4.2.4 on 2024-01-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rate_id_rent_in_catalog_b24_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsbitrix24',
            name='is_reserve_site_field_code_b24',
            field=models.CharField(default='UF_CRM_0000000000', help_text='Код поля Бронирование с сайта в Битрикс24 (тип поля Да/Нет)', max_length=20, verbose_name='Код поля Бронирование с сайта'),
        ),
        migrations.AddField(
            model_name='settingsbitrix24',
            name='reserve_field_code_b24',
            field=models.CharField(default='UF_CRM_0000000000', help_text='Код поля Бронирование в Битрикс24 (тип поля Бронирование ресурсов)', max_length=20, verbose_name='Код поля Бронирование'),
        ),
    ]
