# Generated by Django 4.2.4 on 2024-01-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_reserve_deal_id_b24'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('reserve_closed', models.BooleanField(default=False, help_text='Закрыть возможность бронирования на сайте для посетителей, есть возможность только у персонала', verbose_name='Бронирование закрыто')),
                ('reserve_closed_all', models.BooleanField(default=False, help_text='Закрыть возможность бронирования на сайте для всех, есть возможность только у суперпользователя', verbose_name='Бронирование закрыто для всех')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
