# Generated by Django 4.2.4 on 2024-03-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_additionalservices_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('min_price', models.DecimalField(decimal_places=2, default=1000, help_text='Минимальный номинал сертификата', max_digits=10, verbose_name='Минимальный номинал')),
                ('max_price', models.DecimalField(decimal_places=2, default=1000000, help_text='Максимальный номинал сертификата', max_digits=10, verbose_name='Максимальный номинал')),
                ('step_price', models.DecimalField(decimal_places=2, default=1000, help_text='Шаг для изменения номинала сертификата', max_digits=10, verbose_name='Шаг')),
                ('header_image', models.ImageField(blank=True, help_text='Изображение отображается в шапке карточки на странице Подарочные сертификаты', upload_to='img/giftcert/', verbose_name='Файл основного изображения')),
                ('send_email', models.BooleanField(default=True, help_text='Отправлять информацию по заказанным сертификатам на email. Обязательно укажите его в настройках', verbose_name='Отправлять на email')),
                ('email', models.EmailField(blank=True, help_text='Email адрес для отправки информации по заказанным сертификатам', max_length=254, verbose_name='Email адрес')),
                ('send_b24', models.BooleanField(default=False, help_text='Создавать в Битрикс24 сделки по заказанным сертификатам', verbose_name='Отправлять в Битрикс24')),
                ('id_catalog_b24', models.PositiveIntegerField(blank=True, help_text='ID товара в каталоге Битрикс24', verbose_name='ID товара')),
            ],
            options={
                'verbose_name': 'Подарочный сертификат',
                'verbose_name_plural': 'Подарочные сертификаты',
            },
        ),
        migrations.AddField(
            model_name='settingsbitrix24',
            name='stage_id_for_gift_cert',
            field=models.CharField(default=6, help_text='ID стадии воронки сделок для создания сделки по подарочному сертификату с сайта в CRM', max_length=10, verbose_name='ID стадии для создания сделки по подарочному сертификату'),
        ),
    ]
