# Generated by Django 4.2.4 on 2024-03-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_giftcertificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcertificate',
            name='id_catalog_b24',
            field=models.PositiveIntegerField(help_text='ID товара в каталоге Битрикс24', null=True, verbose_name='ID товара'),
        ),
    ]
