# Generated by Django 4.2.4 on 2024-03-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_giftcertificate_id_catalog_b24'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcertificate',
            name='id_catalog_b24',
            field=models.PositiveIntegerField(blank=True, help_text='ID товара в каталоге Битрикс24', null=True, verbose_name='ID товара'),
        ),
    ]
