# Generated by Django 4.2.4 on 2024-03-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_giftcertificatetype_giftcertificate_validity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcertificate',
            name='header_image',
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Изображение отображается в фоне карточки Подарочного сертификата', upload_to='img/giftcert/', verbose_name='Файл фонового изображения'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='text_color',
            field=models.CharField(choices=[(None, 'Не выбрано'), ('white', 'Белый'), ('dark', 'Черный')], default='dark', max_length=10, verbose_name='Цвет текста в карточке'),
        ),
    ]
