# Generated by Django 4.2.4 on 2024-04-02 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_giftcertificate_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergiftcertificate',
            name='gift_certificate',
            field=models.ForeignKey(default=1, help_text='Из какого подарочного сертификата был создан заказ. Служебное поле для определения начальных параметров', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.giftcertificate', verbose_name='Подарочный сертификат'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='text_color',
            field=models.CharField(choices=[(None, 'Не выбрано'), ('white', 'Белый'), ('dark', 'Черный'), ('shadow', 'Белый с черной обводкой')], default='dark', max_length=10, verbose_name='Цвет текста в карточке'),
        ),
    ]
