# Generated by Django 4.2.4 on 2024-04-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_ordergiftcertificate_gift_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergiftcertificate',
            name='user_address',
            field=models.CharField(blank=True, help_text='Адрес доставки сертификата клиенту', max_length=255, verbose_name='Адрес клиента'),
        ),
        migrations.AddField(
            model_name='ordergiftcertificate',
            name='user_email',
            field=models.EmailField(blank=True, help_text='Электронная почта клиента', max_length=254, verbose_name='Email клиента'),
        ),
    ]
