# Generated by Django 4.2.4 on 2024-04-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_ordergiftcertificate_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergiftcertificate',
            name='user_lastname',
            field=models.CharField(blank=True, help_text='Фамилия клиента', max_length=255, verbose_name='Фамилия клиента'),
        ),
        migrations.AddField(
            model_name='ordergiftcertificate',
            name='user_name',
            field=models.CharField(blank=True, help_text='Имя клиента', max_length=255, verbose_name='Имя клиента'),
        ),
    ]
