# Generated by Django 4.2.4 on 2024-04-12 04:26

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_ordergiftcertificate_user_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcertificate',
            name='background_image',
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='background_image_card',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Изображение отображается в фоне карточки Подарочного сертификата', keep_meta=True, quality=-1, scale=None, size=[600, 400], upload_to='img/giftcert/', verbose_name='Файл фонового изображения карточки'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='background_image_form',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Изображение отображается в фоне формы Подарочного сертификата', keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='img/giftcert/', verbose_name='Файл фонового изображения формы'),
        ),
    ]
