# Generated by Django 4.2.4 on 2024-04-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_giftcertificate_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergiftcertificate',
            name='buy_date_time',
            field=models.DateTimeField(blank=True, help_text='Дата и время оплаты сертификата', null=True, verbose_name='Дата и время оплаты'),
        ),
    ]
