# Generated by Django 4.2.4 on 2024-04-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_ordergiftcertificate_buy_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Описание страницы'),
        ),
        migrations.AddField(
            model_name='company',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='company',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Заголовок страницы'),
        ),
    ]
