# Generated by Django 4.2.4 on 2024-04-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_company_seo_description_company_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaservices',
            name='sort',
            field=models.PositiveSmallIntegerField(default=10, help_text='Чем меньше значение, тем выше будет запись', verbose_name='Сортировка'),
        ),
    ]
