# Generated by Django 4.2.4 on 2024-04-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_spaservices_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergiftcertificate',
            name='used',
            field=models.BooleanField(default=False, help_text='Сертификат уже использован клиентом', verbose_name='Использован'),
        ),
    ]
