# Generated by Django 4.2.4 on 2024-04-22 14:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_ordergiftcertificate_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingssite',
            name='gift_certificate_closed',
            field=models.BooleanField(default=False, help_text='Закрыть возможность оформления подарочного сертификата на сайте для посетителей, есть возможность только у персонала', verbose_name='Сертификаты закрыты'),
        ),
        migrations.AddField(
            model_name='settingssite',
            name='gift_certificate_closed_all',
            field=models.BooleanField(default=False, help_text='Закрыть возможность оформления подарочного сертификата на сайте для всех, есть возможность только у суперпользователя', verbose_name='Сертификаты закрыты для всех'),
        ),
        migrations.AddField(
            model_name='settingssite',
            name='text_gift_certificate_closed',
            field=ckeditor.fields.RichTextField(default='Возможность оформления подарочного сертификата закрыта.', help_text='Текст, который отображается на странице заглушке при закрытой возможности оформления подарочных сертификатов', verbose_name='Текст страницы заглушки'),
        ),
    ]
