# Generated by Django 4.2.4 on 2024-04-24 14:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_settingssite_gift_certificate_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingssite',
            name='text_gift_certificate_ok',
            field=ckeditor.fields.RichTextField(blank=True, default='Спасибо, что вы с нами.', help_text='Текст, который отображается на странице после успешного оформления подарочного сертификата, под параметрами сертификата.', verbose_name='Текст страницы успеха'),
        ),
    ]
