# Generated by Django 4.2.4 on 2024-08-18 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_settingssite_text_gift_certificate_ok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('number', models.PositiveSmallIntegerField(help_text='Порядковый номер дня недели', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Порядковый номер')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='rate',
            name='house',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена за 1 час', max_digits=10, verbose_name='Цена')),
                ('day_period_validity', models.ManyToManyField(help_text='Дни, в которые будет действовать данная цена', to='core.weeks', verbose_name='Период действия, день')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rate',
            name='house',
            field=models.ManyToManyField(related_name='rates', to='core.house', verbose_name='Парная'),
        ),
    ]
