# Generated by Django 4.2.4 on 2024-08-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_weeks_remove_rate_house_price_rate_house'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='weeks',
            options={'verbose_name': 'День недели', 'verbose_name_plural': 'Дни недели'},
        ),
    ]
