# Generated by Django 4.2.4 on 2024-08-18 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_weeks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeks',
            name='number',
            field=models.PositiveSmallIntegerField(error_messages={'unique': 'Убедитесь, что данное значение является уникальным'}, help_text='Порядковый номер дня недели', unique=True, validators=[django.core.validators.MinValueValidator(1, 'Убедитесь что данное значение от 1 до 7'), django.core.validators.MaxValueValidator(7, 'Убедитесь что данное значение от 1 до 7')], verbose_name='Порядковый номер'),
        ),
    ]
