# Generated by Django 4.2.4 on 2024-08-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_rate_id_rent_weekend_in_catalog_b24_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='active',
        ),
        migrations.AddField(
            model_name='rate',
            name='comment',
            field=models.CharField(blank=True, help_text='Рабочий комментарий, например этажность парной', max_length=1024, null=True, verbose_name='Комментарий'),
        ),
    ]
