# Generated by Django 4.2.4 on 2024-08-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_rate_active_rate_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='comment',
            field=models.CharField(blank=True, help_text='Рабочий комментарий, например этажность парной', max_length=1024, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
