# Generated by Django 4.2.4 on 2024-08-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_rate_comment_alter_rate_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='cost_include',
        ),
    ]
