# Generated by Django 4.2.4 on 2024-10-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_reserve_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingssite',
            name='reserve_interval',
            field=models.PositiveSmallIntegerField(default=60, help_text='Интервал бронирования в минутах', verbose_name='Интервал бронирования'),
        ),
        migrations.AddField(
            model_name='settingssite',
            name='reserve_show_interval',
            field=models.PositiveSmallIntegerField(default=30, help_text='Интервал показа бронирования в минутах', verbose_name='Интервал показа бронирования'),
        ),
    ]
