# Generated by Django 4.2.4 on 2024-10-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_settingssite_reserve_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cleaning',
            field=models.PositiveSmallIntegerField(default=30, help_text='Если 0, то уборка отсутствует', verbose_name='Время на уборку в минутах'),
        ),
    ]
