# Generated by Django 4.2.4 on 2024-10-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_house_cleaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='min_time',
            field=models.PositiveSmallIntegerField(default=180, help_text='Минимальное время парения в минутах', verbose_name='Минимальное время парения'),
        ),
    ]
