# Generated by Django 4.2.4 on 2024-10-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_rate_min_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена за интервал бронирования, который задается в настройках сайта', max_digits=10, verbose_name='Цена'),
        ),
    ]
