# Generated by Django 4.2.4 on 2023-09-04 07:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlockBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование блока')),
                ('active', models.BooleanField(default=False, help_text='Выберите блок в качестве активного. Текущий активный блок потеряет этот статус', verbose_name='Активность')),
                ('header', models.CharField(blank=True, help_text='Введите заголовок блока', max_length=255, verbose_name='Заголовок блока')),
                ('second_header', models.CharField(blank=True, help_text='Введите подзаголовок блока', max_length=255, verbose_name='Подзаголовок блока')),
                ('background_image', models.ImageField(upload_to='media/img/booking', verbose_name='Фоновое изображение')),
            ],
            options={
                'verbose_name': 'Блок Бронирование',
                'verbose_name_plural': 'Блоки Бронирование',
            },
        ),
        migrations.CreateModel(
            name='ContentBlockMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование блока')),
                ('active', models.BooleanField(default=False, help_text='Выберите блок в качестве активного. Текущий активный блок потеряет этот статус', verbose_name='Активность')),
                ('header', models.CharField(help_text='Введите заголовок главного баннера', max_length=255, verbose_name='Заголовок главного баннера')),
                ('second_header', models.CharField(help_text='Введите подзаголовок главного баннера', max_length=255, verbose_name='Подзаголовок главного баннера')),
                ('video_mp4', models.FileField(help_text='Выберите видео файл в формате mp4', upload_to='media/video/contentblockmain/', validators=[django.core.validators.FileExtensionValidator(['mp4'])], verbose_name='Видео файл mp4')),
            ],
            options={
                'verbose_name': 'Главный баннер',
                'verbose_name_plural': 'Главные баннеры',
            },
        ),
        migrations.CreateModel(
            name='ContentBlockRoundedMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование элемента')),
                ('image', models.ImageField(upload_to='media/img/roundedmenu', verbose_name='Иконка элемента')),
                ('image_alt', models.CharField(max_length=50, verbose_name='Alt описание')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на страницу')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='ContentBlockYandexMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование блока')),
                ('active', models.BooleanField(default=False, help_text='Выберите блок в качестве активного. Текущий активный блок потеряет этот статус', verbose_name='Активность')),
                ('header', models.CharField(blank=True, help_text='Введите заголовок блока', max_length=255, verbose_name='Заголовок блока')),
                ('second_header', models.CharField(blank=True, help_text='Введите подзаголовок блока', max_length=255, verbose_name='Подзаголовок блока')),
                ('link', models.URLField(help_text='Только ссылка, без тегов', verbose_name='Ссылка на Яндекс карту')),
            ],
            options={
                'verbose_name': 'Блок Яндекс карта',
                'verbose_name_plural': 'Блоки Яндекс карта',
            },
        ),
        migrations.CreateModel(
            name='HouseShowBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('position_top', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Значение не должно быть меньше 0'), django.core.validators.MaxValueValidator(100, 'Значение не должно быть больше 100')], verbose_name='Отступ сверху')),
                ('position_left', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Значение не должно быть меньше 0'), django.core.validators.MaxValueValidator(100, 'Значение не должно быть больше 100')], verbose_name='Отступ слева')),
                ('block_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.contentblockbooking', verbose_name='Блок Бронирования')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house', verbose_name='Парная')),
            ],
            options={
                'verbose_name': 'Расположение Парных на блоке Бронирования',
            },
        ),
        migrations.CreateModel(
            name='ContentBlockService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование блока')),
                ('active', models.BooleanField(default=False, help_text='Выберите блок в качестве активного. Текущий активный блок потеряет этот статус', verbose_name='Активность')),
                ('header', models.CharField(blank=True, help_text='Введите заголовок блока', max_length=255, verbose_name='Заголовок блока')),
                ('second_header', models.CharField(blank=True, help_text='Введите подзаголовок блока', max_length=255, verbose_name='Подзаголовок блока')),
                ('items', models.ManyToManyField(to='mainpage.contentblockroundedmenuitem', verbose_name='Элементы')),
            ],
            options={
                'verbose_name': 'Блок Дополнительные услуги',
                'verbose_name_plural': 'Блоки Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='ContentBlockInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование блока')),
                ('active', models.BooleanField(default=False, help_text='Выберите блок в качестве активного. Текущий активный блок потеряет этот статус', verbose_name='Активность')),
                ('header', models.CharField(blank=True, help_text='Введите заголовок блока', max_length=255, verbose_name='Заголовок блока')),
                ('second_header', models.CharField(blank=True, help_text='Введите подзаголовок блока', max_length=255, verbose_name='Подзаголовок блока')),
                ('items', models.ManyToManyField(to='mainpage.contentblockroundedmenuitem', verbose_name='Элементы')),
            ],
            options={
                'verbose_name': 'Блок Инфраструктура',
                'verbose_name_plural': 'Блоки Инфраструктура',
            },
        ),
        migrations.AddField(
            model_name='contentblockbooking',
            name='houses',
            field=models.ManyToManyField(through='mainpage.HouseShowBooking', to='core.house'),
        ),
    ]
