# Generated by Django 4.2.4 on 2023-10-06 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblockbooking',
            name='background_image',
            field=models.ImageField(upload_to='img/booking', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='contentblockmain',
            name='video_mp4',
            field=models.FileField(help_text='Выберите видео файл в формате mp4', upload_to='video/contentblockmain/', validators=[django.core.validators.FileExtensionValidator(['mp4'])], verbose_name='Видео файл mp4'),
        ),
        migrations.AlterField(
            model_name='contentblockroundedmenuitem',
            name='image',
            field=models.ImageField(upload_to='img/roundedmenu', verbose_name='Иконка элемента'),
        ),
    ]
