# Generated by Django 4.2.4 on 2024-10-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_houseshowbooking_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToastMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование блока')),
                ('active', models.BooleanField(default=False, help_text='Выберите блок в качестве активного. Текущий активный блок потеряет этот статус', verbose_name='Активность')),
                ('header', models.CharField(help_text='Введите заголовок всплывающего окна', max_length=50, verbose_name='Заголовок')),
                ('second_header', models.CharField(help_text='Введите подзаголовок всплывающего окна', max_length=50, verbose_name='Подзаголовок')),
                ('image', models.ImageField(help_text='Загрузите картинку-баннер', upload_to='img/toasts/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Всплывающее окно',
                'verbose_name_plural': 'Всплывающие окна',
            },
        ),
    ]
