# Generated by Django 4.2.4 on 2023-12-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=79832912475, max_length=20, unique=True, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
