# Generated by Django 4.2.4 on 2023-11-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_additionalservices'),
        ('staticpages', '0002_textcontentcorporate_textcontentspa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('seo_title', models.CharField(blank=True, max_length=60, verbose_name='Заголовок страницы')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='Описание страницы')),
                ('seo_keywords', models.CharField(blank=True, max_length=100, verbose_name='Ключевые слова')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('header', models.CharField(help_text='Введите заголовок', max_length=255, verbose_name='Заголовок')),
                ('second_header', models.CharField(help_text='Введите подзаголовок', max_length=255, verbose_name='Подзаголовок')),
                ('active', models.BooleanField(default=False, help_text='Выберите в качестве активного. Текущий активный элемент потеряет этот статус', verbose_name='Активность')),
                ('header_image', models.ImageField(blank=True, upload_to='img/price/', verbose_name='Файл основного изображения')),
                ('header_house', models.CharField(max_length=1024, verbose_name='Заголовок для основных услуг')),
                ('description_house', models.CharField(max_length=1024, verbose_name='Описание для основных услуг')),
                ('header_service', models.CharField(max_length=1024, verbose_name='Заголовок для дополнительных услуг')),
                ('description_service', models.CharField(max_length=1024, verbose_name='Описание для дополнительных услуг')),
                ('house', models.ManyToManyField(help_text='Выберите парные для отображения на странице Цены в основных услугах', related_name='house_content_price', to='core.house', verbose_name='Парные')),
                ('service', models.ManyToManyField(help_text='Выберите дополнительные услуги', related_name='service_content_price', to='core.additionalservices', verbose_name='Дополнительные услуги')),
            ],
            options={
                'verbose_name': 'Контент для страницы Цены',
                'verbose_name_plural': 'Контент для страницы Цены',
            },
        ),
    ]
