# Generated by Django 4.2.4 on 2023-11-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_additionalservices'),
        ('staticpages', '0003_contentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprice',
            name='description_house',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание для основных услуг'),
        ),
        migrations.AlterField(
            model_name='contentprice',
            name='description_service',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание для дополнительных услуг'),
        ),
        migrations.AlterField(
            model_name='contentprice',
            name='service',
            field=models.ManyToManyField(blank=True, help_text='Выберите дополнительные услуги', related_name='service_content_price', to='core.additionalservices', verbose_name='Дополнительные услуги'),
        ),
    ]
