# Generated by Django 4.2.4 on 2023-12-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0005_contentspa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextContentSpa',
        ),
    ]
