# Generated by Django 4.2.4 on 2024-04-10 15:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0009_contentgiftcertificate_delete_textcontentcert'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgiftcertificate',
            name='content_image',
            field=models.ImageField(blank=True, help_text='Изображение сразу после сертификатов', upload_to='img/giftcert/', verbose_name='Файл изображения'),
        ),
        migrations.AddField(
            model_name='contentgiftcertificate',
            name='content_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Текст после изображения', verbose_name='Текст страницы'),
        ),
    ]
