# Generated by Django 4.2.4 on 2024-04-10 15:39

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0010_contentgiftcertificate_content_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentgiftcertificate',
            name='content_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Изображение сразу после сертификатов', keep_meta=True, quality=-1, scale=None, size=[800, 600], upload_to='img/giftcert/', verbose_name='Файл изображения'),
        ),
    ]
